development:
  clients:
    default:
      database: paas
      hosts:
        - 127.0.0.1:27017

test:
  clients:
    default:
      database: paas_test
      hosts:
        - 127.0.0.1:27017

production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] %>
